[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[fuzz]
runs = 256
# max_test_rejects=100000

[invariant]
runs = 1
depth = 32
fail_on_revert = true



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
